### ISSUE TITLE
Your location actually does appear but only given a certain circumstance

### ISSUE THREAD

**Issue by kwokwilliam** [dajuniors/phase5#12]
If you refresh the page and try to wait for it, your location as the blue dot won't appear....but if you try do the same thing except this time switch tabs to a different tab and go back, it WILL be there. This is not due to a state issue as well, because even as the animation is going on if you switch the tabs it will appear even in the middle of the animation.

In google chrome, anyways

**Comment by kathlu** [comment]
This was a bug we tried really hard to fix. After hours of searching for resources and testing various options, we were unable to fix this bug. We believe the logic to be correct but cannot figure out why the current location dot only appears after a refresh or switching tabs. The functionality for current location works, but I am unsure of why the layer which renders the dot only appears after a certain circumstance. We were unable to find a similar question on the internet to answer our question. Maybe if we had more time, we could reach out to people to provide a second opinion on this problem or submit a support request to Mapbox. https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231
There were some possibilities we thought about to fix this problem, such as, changing location services API or restructuring our code, which we simply do not have time for as we do not want to mess up the functionalities that we have succeed. We did our best during the time we were provided but we're unsuccessful with finding a fix.
