### ISSUE TITLE
When clicking get directions, then changing tabs, the animation to your current location only happens when switching back to the tab.

### ISSUE THREAD

**Issue by kwokwilliam** [dajuniors/phase5#13]

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/commit/40486c08b6e03fdfa6ae314251b4c4ae768f3657
https://github.com/dajuniors/phase5/commit/0577b0d6a3d4ddf2c64c9f559a3a9342b7c86298

Fixed! The map should not have zoomed into the current location after switching to and from website to a different tab. We added a go to location button so users can navigate to their current location if needed.
