### ISSUE TITLE
Doesn't show my locations restrooms

### ISSUE THREAD

**Issue by aliar97** [dajuniors/phase5#14]
When my location is Bellevue Washington, it only shows restrooms in the UW area. I would say this is a major bug as it does not show me where I can find a restroom close to me in my current location. To reproduce this try setting your location on the east side somewhere and see if you can get any results

**Comment by kathlu** [comment]
The data used in our application is gathered by us personally. We went to each of the bathrooms and gathered the information of coordinates and features. We decided to focus only on bathrooms on UW Campus as it was the most feasible option. 
Maybe in future releases we can gather more data around Seattle/WA/US or allow for crowd-sourcing. As of now, we are only able to provide data on UW Campus.
