### ISSUE TITLE
Directions don't say what street to turn on

### ISSUE THREAD

**Issue by emilytao19** [dajuniors/phase5#2]
<img width="431" alt="Screen Shot 2019-06-10 at 4 15 59 PM" src="https://user-images.githubusercontent.com/32439428/59232897-2052cd80-8b9b-11e9-87d7-b931ec805a87.png">

**Comment by emilytao19** [comment]
1. Click on Sieg Hall
2. Starting location is 1818 NE 45th St Seattle WA 98105
3. View directions
4. The directions are too vague to follow because only one of the lines tells you what street to turn on

**Comment by kathlu** [comment]
`impossible` Yes, these directions are too vague. Unfortunately, there is no way for us to fix this issue. We use the Mapbox Navigation API to keep consistent with the use of Mapbox API for our map and other features. We call the Mapbox Navigation API to provide us direction between two coordinates. Some steps may have street names, while others do not. Mapbox simply does not have the information to provide us with the street names to fix this issue. The API is the only feasible way for us to get directions and we can only work with what Mapbox provides us.
