### ISSUE TITLE
Titles aren't consistent

### ISSUE THREAD

**Issue by bnguyen12** [dajuniors/phase5#22]
Titles aren't consistent between similar titles. If you open the application, scroll all the way down, you'll find two "Thomson Hall (Floor 2-4)." One is for men and the other is for women, however their titles look like this:

women's:
Thomson Hall (Floor 2-4
)

men's:
Thomson Hall (Floor 2-
4)

**Comment by kathlu** [comment]
This does not affect the functionality or use of the application. This is just a design issue, so we marked this as a non-failure.
