### ISSUE TITLE
When I selected a bathroom Location doesn't focus to the location

### ISSUE THREAD

**Issue by jinc132** [dajuniors/phase5#23]
After I selected my location and the arrow button to get my direction and I select the Paccar bathroom location. The map does not refocus to where the paccar bathroom. It was super zoomed out and clustered with other bathroom locations. This made it difficult to understand which one I selected.

**Comment by lbc546** [comment]
If the user zooms out of the map to look for other bathrooms, then they should be able to zoom into that bathroom’s location. We do not zoom in because we already calculated distance from the bathroom the user initially wanted to find the directions to the bathroom for.
