### ISSUE TITLE
Lack of information makes this app very confusing

### ISSUE THREAD

**Issue by sKhan16** [dajuniors/phase5#24]
Minor: When I am accessing this application from a city far away from Seattle (Federal Way), the application doesn’t display restrooms that are near me, instead they show restrooms that are near UW. There is no indication that this app only finds bathrooms near UW. There should be some indication of this fact if the applications main purpose is to only display bathrooms at UW. If this is not the case, then that changes the severity of the issue to a major one. As it should be showing bathrooms that are near the user as well as UW.

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/issues/14

**Comment by kathlu** [comment]
As stated in the previous issue, we collect the data ourselves. It is not feasible for us to travel to each bathroom and gather the data, which is why we focused our scope to UW campus specifically.
