### ISSUE TITLE
Not sure about the right format of address input

### ISSUE THREAD

**Issue by yiranni** [dajuniors/phase5#25]
I tried to enter an address, but it tells me "Error: Cannot locate the address you have entered. Please enter the full address of your starting location." What would be the right format for the full address? 
![image](https://user-images.githubusercontent.com/32496771/59305145-8187a900-8c4e-11e9-93b6-bc242c1f857b.png)

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/issues/4
https://github.com/dajuniors/phase5/commit/bc160ccb9ba5d83bb3f2a4888fec03a2ee20195a
This issue has been fixed. We previously placed restrictions to limit starting addresses to UW campus only. Users can now input starting address from anywhere.
