### ISSUE TITLE
No user feedback after denying initial location prompt

### ISSUE THREAD

**Issue by vincentmvdm** [dajuniors/phase5#27]
If a user denies the initial location prompt, there is no indication anywhere in the app that they have done this. It should say "You have denied location services. Please go to your browser settings and enable location services for this website." Instead, there is no message and the app still pretends it knows my location by showing "your location" in the legend.

Steps to reproduce:

1. Click "deny" on the initial location prompt
2. Observe the effect described above

**Comment by navjanar1** [comment]
Legend now informs user if location was not provided

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/commit/c414cc0d205852380f91e41400f7f84cf03801b3
