### ISSUE TITLE
Logo does not have enough contrast with surrounding elements

### ISSUE THREAD

**Issue by vincentmvdm** [dajuniors/phase5#30]
The logo is used to communicate the app's purpose to users. However, the logo's key element (the toilet) is pure black (#000000) while the logo sits on a purple (#4b2e83) background. That makes the toilet almost impossible to see for people with less than perfect vision.

[Here](http://jxnblk.com/colorable/demos/text/?background=%234b2e83&foreground=%23000000) is the contrast report in question. 

Steps to reproduce: 
- Go to the app and notice the black icon on a purple background

Steps to resolve:
- Improve the contrast of the logo's main brand element by, for instance, making it white or gold

**Comment by kathlu** [comment]
This has no impact on the functionality. We marked this issue as a non-failure.
