### ISSUE TITLE
Legend features icons ("key required") that the map doesn't use

### ISSUE THREAD

**Issue by vincentmvdm** [dajuniors/phase5#31]
The legend shows all the same icons ("disability access", "key required") as the sidebar, but these icons are not used on the map. The map only uses the restroom icon (the red pin). In other words, the legend has superfluous information and that is both confusing and distracting.

Steps to reproduce:
- Navigate to the app and observe that, without any filters selected, not a single icon (except for the red pin) shows up on the map

Steps to resolve:
- Only include icons in the legend that the map actually uses

**Comment by lbc546** [comment]
The legend is there for both maps and sidebar. Could be design issue but not failure.
Possible enhancement.

**Comment by lbc546** [comment]
Decision changed, moved to icons
