### ISSUE TITLE
URL does not change upon app selection, making it impossible to share restrooms

### ISSUE THREAD

**Issue by vincentmvdm** [dajuniors/phase5#32]
When a user selects a restroom by clicking on it in the sidebar, the app's map centers on that restroom but the URL does not change. Initially, the app URL is https://dajuniors.github.io/phase5/ and when I click on the Bloedel Hall (Floor 1) restroom it stays https://dajuniors.github.io/phase5/. That is problematic because it makes it impossible for users to share restrooms with friends and family. That feature is essential for acquisition and important for events such as graduation.

Steps to reproduce:
1. Open the app and observe that the URL is https://dajuniors.github.io/phase5/
2. Select a restroom and observe that the URL stays https://dajuniors.github.io/phase5/
3. Observe that this means that you can not share restrooms or easily go back to a restroom later by bookmarking it

Desired behavior:
1. Open the app and observe that the URL is https://dajuniors.github.io/phase5/
2. Select a restroom and observe that the URL becomes https://dajuniors.github.io/phase5/restrooms/restroomID
3. Observe that this means that you can share restrooms and easily go back to a restroom later by bookmarking it

**Comment by kathlu** [comment]
This is not a functionality that we decided to have. This is rather a suggestion for future features, therefore, we will be marking this issue as a non-failure.
