### ISSUE TITLE
App never displays a building's complete address

### ISSUE THREAD

**Issue by vincentmvdm** [dajuniors/phase5#33]
The app displays the address of a restroom's building in the sidebar, but does not display the full address and instead just provides the street name. For instance, Elm's restroom is said to be on NE Campus Parkway. Even when you click on a restroom, the app doesn't give you the full address and instead only allows you to get the directions. This matters because a) an address like "NE Campus Parkway" is not specific enough to navigate to the building in question and b) this makes it impossible to the use the app in tandem with a 3rd party navigation service such as Google Maps.

Steps to reproduce:
1. Open the app
2. Select the Elm Hall restroom and notice that the address doesn't get more specific than "NE Campus Parkway"

Desired behavior

1. Open the app
2. Select the Elm Hall restroom and notice that the popover on the map has the full building address: 1218 NE Campus Pkwy, Seattle, WA 98105

**Comment by kathlu** [comment]
We updated the data on our firebase. Although, we were not able to find physical building addresses for some of the buildings on campus, in which we inputed the street in which the building is located on or next to.
