### ISSUE TITLE
Master detail-view is reversed (sidebar is on the right)

### ISSUE THREAD

**Issue by vincentmvdm** [dajuniors/phase5#34]
The app uses one of the most commonly used UI patterns: a master-detail view. Users can select a restroom in the master view and see the detail view (the map) reflect their selection. However, this detail view has been reversed. In countries where the reading direction is left to right, it is standard to display the master view on the left and the detail view on the right. Every modern app (e.g. see https://scout.uw.edu/seattle/, but also Airbnb and many more) adheres to this standard and going against it can be confusing to users.

Steps to reproduce:

1. Open the app and notice how the master view is on the right while the detail view is on the left
2. Notice how this is not in line with most modern apps

Desired behavior:

1. Open the app and notice how the master view is on the left while the detail view is on the right
2. Notice how this is in line with most modern apps

**Comment by kathlu** [comment]
This has no impact on the functionality.  It is rather a design critique, which we have decided not to fix for the purpose of this assignment.
