### ISSUE TITLE
Blue path that is drawn is incorrect

### ISSUE THREAD

**Issue by emilytao19** [dajuniors/phase5#4]
Used 1818 NE 45th St Seattle WA 98105 as a starting address and the blue line connecting the starting location and the final location of the restroom (Poplar Hall) did not start in the correct place. The house is on 19th and 45th and it started me somewhere by the Burke Museum. 
<img width="491" alt="Screen Shot 2019-06-10 at 4 21 23 PM" src="https://user-images.githubusercontent.com/32439428/59233118-fcdc5280-8b9b-11e9-81c0-9a302383e840.png">

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/commit/bc160ccb9ba5d83bb3f2a4888fec03a2ee20195a
Previously, we decided to limit the starting address to be within UW Campus. We got rid of the 'bbox' that limited the search query locations. Users can now input starting address from anywhere.

<img width="548" alt="Screen Shot 2019-06-10 at 7 11 43 PM" src="https://user-images.githubusercontent.com/26660940/59238629-abd85880-8bb3-11e9-8826-61c8ecabe780.png">
