### ISSUE TITLE
Inconsistent key required tag

### ISSUE THREAD

**Issue by emilytao19** [dajuniors/phase5#5]
1. Select gender neutral bathrooms as well as male bathrooms
2. Click on Sieg Hall
3. It says that key is required on the map
4. Also select key required
5. Sieg Hall disappears even though the map previously said that key was required for Sieg
<img width="1064" alt="Screen Shot 2019-06-10 at 4 24 27 PM" src="https://user-images.githubusercontent.com/32439428/59233284-a6bbdf00-8b9c-11e9-8014-1475ee5cfd21.png">

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/commit/b6132d847abf93311993fcde6d6347739e9c53e4
