### ISSUE TITLE
Directions from San Francisco aren't displayed

### ISSUE THREAD

**Issue by MatthewSVogt** [dajuniors/phase5#6]
Clicking on "get directions" from the geolocation (Latitude: 37.774929, Longitude: -122.419416) doesn't provide any directions and doesn't give any notifications that directions can't be provided from this location. 
The console shows an uncaught promise. 
Geolocation can be set through chrome dev tools, within the sensors tab.

**Comment by kathlu** [comment]
The distance between San Francisco and UW are way to far for walking directions. Mapbox does not allow for directions for this far of a route. We added an error popup to inform the user.

Realistically, users will not be locating directions across different states or such far distances. Although, this prompted an issue of providing an error message which has been added. Thanks!
