### ISSUE TITLE
Map keeps snapping back to current location

### ISSUE THREAD

**Issue by Jimmt** [dajuniors/phase5#7]
If location is enabled, the map will occasionally snap back to your location (panning and zooming), even if you're trying to look somewhere else on the map. This seems to happen in set time intervals, without end.

**Comment by Jimmt** [comment]
https://youtu.be/MEwTVWVjkrQ

Shows this issue happening a couple of times.

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/commit/40486c08b6e03fdfa6ae314251b4c4ae768f3657

Issue Fixed. map.FlyTo will only "fly" to location upon first retrieval of user current location.
