### ISSUE TITLE
"Your Location" does not show up on the map

### ISSUE THREAD

**Issue by yiranni** [dajuniors/phase5#8]
![image](https://user-images.githubusercontent.com/32496771/59234508-f2bd5280-8ba1-11e9-8d16-94899bcfa310.png)

**Comment by kathlu** [comment]
There really is no context to understand this bug. As Andy mentioned in the debugging reading, "When bug reports lack clear reproduction steps, bugs often can't be fixed." There are many questions as to what the user was doing for the "Your location" not showing up on the map. Did the user allow or block their location? Where is their actual location?  If the user blocked their location, should the 'your location' marker be present in the legend? Was the user expecting to see 'your location'? Considering the user is zoomed out, is the location marker too small for the user to see?  We are unable to resolve the bug as we do not have enough information to reproduce this bug.
