### ISSUE TITLE
Radio Buttons Unclear

### ISSUE THREAD

**Issue by Dudethq** [dajuniors/phase5#9]
I was not sure what the radio buttons were doing. I originally thought that they were supposed to add only those kinds of bathrooms to the map, however I soon realized that was not the case. It took me a while before understanding a little bit better that they are in some sort of way filtering the bathrooms in some way.

**Comment by lbc546** [comment]
[https://github.com/dajuniors/phase5/commit/694b5337ae60c4b38a1c4b9acd1cd0f1408997ce](url)

Fixed #9 #
